### ISSUE TITLE
Issue regarding tessarcat_motion_planning

### ISSUE THREAD

**Issue by LuciferMorningStar0786** [srsidd/tesseract_docker_image#1]
Hi Sir,

Me trying out Tesseract Motion planning for UR10e for surface tool planning above circular cylinder to clean the mud above it, So can you help me out in that:

1. To create noether_tool_path_generator on .stl file. (I am able to generate on .ply file). Basically we have cad model so no using of depth_camera for scanning.
2. ROS1_bridging with noether_pkg.
3. To  create a work-cell of a Universal Robot UR10e  in URDF and SRDF file  (I am able to control UR10e using ROS2_controller_node, and Moveit)... I want to explore more in tessract_motion_planning.
4. And to integrate snp_motion_planning and snp_motion_execution to it my own robotic cell.  

**I am using foxy for (UR10e contoller and Tesseract_ros2) and noetic for (noether_tool_path_generator)**

Please reach out to me, your advice will be beneficial to my project.

**Comment by srsidd** [comment]
This repository only houses a docker image for tesseract. As such if you're interested in the workings of tesseract, you should probably look at the documentation [here](https://industrial-training-master.readthedocs.io/en/humble/_source/session8/Motion-Planning-with-Tesseract.html#running-the-application) or go through the codebase on the [tesseract repository](https://github.com/tesseract-robotics/tesseract). Closing this issue.
